### ISSUE TITLE
Non intuitive documentation

### ISSUE THREAD

**Issue by stephane98** [pinax/pinax-comments#28]
**Hello**

Is it possible to have a clear documentation of pinax-comments app?

**Comment by KatherineMichel** [comment]
Is there a question about pinax-comments in particular that I could help you with?

**Comment by stephane98** [comment]
Thanks @KatherineMichel.

How I supposed to use pinax-comments Comment model? 
How I supposed to load templates tags?

**Comment by KatherineMichel** [comment]
@stephane98 I intended to help you personally, but you'd be best served by joining our Slack channel and asking in the help channel, where there is a community of people who can provide help. http://slack.pinaxproject.com/

**Comment by KatherineMichel** [comment]
Hi @stephane98, was this resolved?

**Comment by KatherineMichel** [comment]
We have docs on our list of future improvements. Closing for now, but feel free to ask questions in Slack.

**Comment by st9-8** [comment]
Hello thanks for the following up.

I found another solution. But I will come back on pinax-comments later.

The documentation will be welcome 🤗

Stéphane Fedim


Le dim. 19 juil. 2020 à 20:47, KatherineMichel <notifications@github.com> a
écrit :
